### ISSUE TITLE
Where is the tables sql?

### ISSUE THREAD

**Issue by hoomey** [doomhz/coinnext#5]
code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  index: 0,
  sql: 'SELECT * FROM `events` WHERE `events`.`status`=1 AND `events`.`type` IN (2,4) ORDER BY `created_at` ASC LIMIT 1;'

**Comment by alidiepuit** [comment]
@hoomey do you have this database?

**Comment by bitcoinli** [comment]
?
